/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f5f3f9",
        "error": "#ba1a1a",
        "surface-bright": "#fbf8fe",
        "inverse-on-surface": "#f2f0f6",
        "tertiary-fixed": "#d5e3ff",
        "surface-variant": "#e3e1e7",
        "on-surface": "#1b1b20",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "surface": "#fbf8fe",
        "surface-dim": "#dbd9df",
        "secondary-fixed-dim": "#b7c4ff",
        "surface-container": "#efedf3",
        "on-secondary-container": "#082d8d",
        "tertiary-fixed-dim": "#a7c8ff",
        "on-secondary-fixed-variant": "#213e9d",
        "on-secondary-fixed": "#001552",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#00164f",
        "on-error-container": "#93000a",
        "background": "#fbf8fe",
        "inverse-primary": "#b6c4ff",
        "secondary": "#3d57b6",
        "on-tertiary-fixed-variant": "#1b477d",
        "tertiary-container": "#00244b",
        "on-background": "#1b1b20",
        "primary-container": "#081f5c",
        "on-error": "#ffffff",
        "outline": "#757681",
        "primary-fixed": "#dce1ff",
        "primary-fixed-dim": "#b6c4ff",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#4a5b9a",
        "secondary-container": "#829bfe",
        "secondary-fixed": "#dce1ff",
        "surface-container-high": "#e9e7ed",
        "surface-container-highest": "#e3e1e7",
        "tertiary": "#000f25",
        "inverse-surface": "#303035",
        "on-primary-fixed-variant": "#314380",
        "on-tertiary-container": "#668dc7",
        "outline-variant": "#c5c5d1",
        "on-primary-container": "#7789cb",
        "error-container": "#ffdad6",
        "on-surface-variant": "#454650",
        "primary": "#000b34",
        "on-tertiary-fixed": "#001b3b"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "xxl": "80px",
        "gutter": "24px",
        "container-max": "1280px",
        "sm": "8px",
        "unit": "4px",
        "lg": "24px",
        "md": "16px",
        "xl": "48px",
        "xs": "4px"
      },
      fontFamily: {
        "headline-lg": ["Playfair Display"],
        "display-lg-mobile": ["Playfair Display"],
        "display-lg": ["Playfair Display"],
        "headline-md": ["Playfair Display"],
        "body-md": ["DM Sans"],
        "body-lg": ["DM Sans"],
        "label-caps": ["DM Sans"]
      },
      fontSize: {
        "headline-lg": ["32px", { "lineHeight": "1.3", "fontWeight": "400" }],
        "display-lg-mobile": ["40px", { "lineHeight": "1.2", "fontWeight": "400" }],
        "display-lg": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "1.2", "letterSpacing": "0.15em", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
